# welcome to SupremeEconomy's config, here you change also everything in the plugin relevant to player/plugin settings.
# if you need any extra help please join my support discord:
# in-game messages can be edited in 'messages.yml'
t:
  # mysql data settings.
  # make sure you can check your panel database info to make sure everything is correct.
  data:
    # types: [H2 OR MYSQL]
    type: 'H2'

    # The address for the database server.
    # - to enable this part, change type to 'MYSQL'
    # - some hosts can use your domain or server ip.
    address: 'host'
    # The standard DB engine port is used by default
    port: 3306
    # The name of the database to store Token data in.
    database: 'database'
    # Credentials for the database.
    username: 'user'
    password: 'pass'
    useSSL: false

  plugin:
    commands:
      money:
        command: 'money'
        aliases:
          - 'tokens'
          - 'coins'
          - 'gems'
    # how many entries should /tbaltop pull. Recommended: 1 - 20
    leaderboard-entries: 10 # 10 will pull the top 10 players who have the most tokens.
    update-stats: 120 # in seconds

  # global restrictions, disable money gain in certain objects.
  restrictions:
    # if a player is in these worlds they will not receive money for events.
    # - players will still be able to send money to other players & use them.
    disabled-worlds:
      - 'lobby'
      - 'resourceworld'

  support:
    # weather SupremeEconomy should be a vault dependency.
    tokeneco-vault-dependency: false
    # allow SupremeEconomy to become the main economy usage, set true if you want SE as your main.
    disable-essentials-eco: false
    # adds support to use base command for SE.
    base-commands:
      pay: false
      balance: false
      baltop: false
      exchange: false
      toggle: false

  # standalone player settings.
  player:
    # the amount of tokens a player will start with.
    starting-balance: 150
    # what's the minimum balance a player can have
    min-balance: 0
    # Max balance a player can have.
    max-balance: 1000000000 # the max money someone can have, only admin commands will be able to bypass this.
    # Minimum amount to be used in /tpay.
    min-pay: 1
    # Maximum amount to be used in /tpay.
    max-pay: 50000000
    bank:
      # starting bank balance a player starts with.
      starting-balance: 0
      # Max bank balance a player can have.
      max-bank: 1000000000 # the max bank balance someone can have, only admin commands will be able to bypass this.
      # Minimum amount someone can deposit.
      min-bank-deposit: 1
      # Maximum amount someone can deposit.
      max-bank-deposit: 50000000
      # Minimum amount someone can withdraw.
      min-bank-withdraw: 1
      # Maximum amount someone can withdraw.
      max-bank-withdraw: 50000000
      # should token exchange use bank balance? if true, this will add to bank money balance.
      exchange-bank-balance: false

    # value = the amount of money it will give the player on completing the events.
    # minus will remove a token from the player example, value: -5 = will remove 5 tokens
    events:
      # weather or not money gain messages will show for events.
      enable-messages: true
      mythic-mob-kill:
        value: 0
      # when a player dies
      player-death:
        value: -1 # minus will remove 'value' amount of money from the player balance
      # when you kill a player.
      kill-players:
        value: 3 # set 0 to disable
      # when you kill a mob.
      kill-entities:
        #<ENTITY_NAME>:
          #value: <tokens to be added>
        # entity: animals
        COW:
          value: 1
        SHEEP:
          value: 1
        CHICKEN:
          value: 1
        RABBIT:
          value: 1
        # entity: mobs
        ZOMBIE:
          value: 1
        SKELETON:
          value: 1
        SPIDER:
          value: 1
        CREEPER:
          value: 2
        SLIME:
          value: 2
        ENDERMAN:
          value: 5
        ENDERDRAGON:
          value: 35
      nether-portal: # this example is how many money it would cost to go in the nether portal
        value: -10
      end-portal: # this example is how many money it would cost to go in the end portal
        value: -20